/** Declaration file generated by dts-gen */

export class BaseObject {
    constructor();

    constructor(params: any);
    init(params: any): any;
    assignValue(key: string, value: any): any
    assignValues(params: any): any;
    getValues(): any;
    getClass(): typeof BaseObject;

}

export const mixin: {
    computed: {
        model: any;
    };
    methods: {
        $commit: any;
        attr: any;
        getModel: any;
    };
    props: {
        store_path: any;
    };
};

export function notNull(obj: any): boolean;

export function isNull(obj: any): boolean;

export function responseOk(response: any): boolean;

export function attr(obj: any, keys: any, default_value: any): any;

export function setAttr(obj: any, keys: any, new_value: any): any;

export function onRouteUpdate(kind: string, to: any, from: any, next: any): any;

export function componentExtend(child: any, parent: any): any;

export function setPageTitle(s: string): any;

export function buildStore(proto: any): any;

export function buildStoreConfig(proto: any): any;

export function findIndexByKey(obj: any, key: any, value: any): any;

export function findItemByKey(obj: any, key: any, value: any): any;

export function getModel(instance: any): any;

export function getMutations(proto: any): any;

export function removeDuplicates(items: any): any;

export function deepClone(obj: any): any;

export function objContains(obj1: any, obj2: any): boolean;

export function objEquals(obj1: any, obj2: any): boolean;

export function urlGetAdd(url: any, key: any, value: any): any;