/** Declaration file generated by dts-gen */

export class BaseObject {
    constructor();

    assignValues(params: any): any;

    getValues(): any;

}

export const mixin: {
    computed: {
        model: any;
    };
    methods: {
        $commit: any;
        attr: any;
        getModel: any;
    };
    props: {
        store_path: any;
    };
};

export function buildStore(proto: any): any;

export function buildStoreConfig(proto: any): any;

export function findIndexByKey(obj: any, key: any, value: any): any;

export function findItemByKey(obj: any, key: any, value: any): any;

export function getModel(instance: any): any;

export function getMutations(proto: any): any;

export function removeDuplicates(items: any): any;

